require: rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - spec/**/*
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 25
Style/Documentation:
  Enabled: false
