require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - vendor/bundle/**/*
Security:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/Syntax:
  Enabled: true

RSpec/Focus:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false
